### ISSUE TITLE
Support for WebGL in UploadItch action

### ISSUE THREAD

**Issue by GeorgeManeta** [Chaser324/unity-build-actions#26]
Apparently UploadItch.cs doesn't have support for uploading builds of the WebGL plataform.

Any channel name input would just get ignored 'cause of the "default" of the switch case statement at line 193 that returns null, resulting in an invalid push command "butler push dir itchName/gameName:"

I suggest adding a case for the WebGL plataform and making the default throw an exception or simply break, so any literal parts of the channel name format still get through.

(currently working around this bug by creating a separate action, filtering by plataform == WEBGL and using the channel override field with a literal "webgl" value)

**Comment by robinnorth** [comment]
Thanks @GeorgeManeta, looks like the Itch Uploader action is in need of a bit of work in general in order to support some of the more recent additions to build platforms (WebGL and UWP support, Android and macOS architecture variants all spring to mind).
