### ISSUE TITLE
namespace 'BuildAction' could not be found

### ISSUE THREAD

**Issue by Estemyr** [Chaser324/unity-build-actions#27]
Trying to create some BuildActions to help development, Have the newest versions of SuperUnityBuild (5.0.1), and BuildActions (2.1.1) through package manager. I've followed the instructions on the wiki, implemented the class and checked the build in ones for differences. The scripts has no errors until I try to start building through SuperUnityBuild where I get this error.

"Assets\SuperUnityBuild\BuildActions\ResetToWindows.cs(1,23): error CS0234: The type or namespace name 'BuildTool' does not exist in the namespace 'SuperUnityBuild' (are you missing an assembly reference?)"

This is only the case for my own buildTools. The build in one seems to work.
The funny thing is that it still seems to run the tools, Debug log at the end of the function runs, but since there's an error, Unity cancels the build and it doesn't produce any actual files...

The script is just a workaround on the errors produced when building to PC after android for unity in general.
"Texture Compression ETC2 is not supported on Standalone"
Example issue: https://forum.unity.com/threads/cache-bleed-between-windows-android-builds-etc1-texture-error-bug.1180903/

So build order for SuperUnityBuild is PC -> Android, then execute this after so that I don't have to manually reset to Standalone to avoid the error.

![Screenshot 2021-12-28 131544](https://user-images.githubusercontent.com/28363698/147565373-676d05e2-95ab-420e-8b08-157ae3016f13.png)

**Comment by robinnorth** [comment]
Hi @Tripleace, is your custom build action in an 'Editor' folder? If not, I believe that will fix this for you. The `SuperUnityBuild.BuildTool` namespace is only available for the 'Editor' platform, which is likely why you'll be seeing these errors on building.

I notice that the wiki doesn't mention this, so I will update it, thanks for flagging it!

The following test build action works for me when added at `Assets/Editor/TestBuildAction.cs` in a Unity 2020.3 test project:

```csharp
using SuperUnityBuild.BuildTool;
using UnityEditor;
using UnityEngine;

public class TestBuildAction : BuildAction, IPostBuildPerPlatformAction, IPostBuildAction
{
    public override void Execute()
    {
        Debug.Log("Test single run build action");
    }

    public override void PerBuildExecute(
            BuildReleaseType releaseType,
            BuildPlatform platform,
            BuildArchitecture architecture,
            BuildDistribution distribution,
            System.DateTime buildTime, ref BuildOptions options, string configKey, string buildPath)
    {
        Debug.Log("Test per-platform build action");
    }
}
```

**Comment by Estemyr** [comment]
Ahh, Yes tried it now and it works, Thanks!
Got a little confused since it seemed to auto-generate a "SuperUnityBuild" folder with a "BuildActions" subfolder in assets, so I assumed that it was at the right spot. 😅

**Comment by robinnorth** [comment]
Ah, another good spot! It should generate an 'Editor' folder under that path too as that is the intended default location for user-provided build actions. Before the tool switched to using assembly definitions, the 'Editor' folder wasn't necessary, so the default path didn't include it. I will push a fix for that.

**Comment by robinnorth** [comment]
I've just pushed https://github.com/superunitybuild/buildtool/releases/tag/v5.0.2 which includes a fix for the default user Build Actions path for new installs.

To upgrade your existing installation, create an 'Editor' folder under the 'SuperUnityBuild' folder, so that the path `Assets/SuperUnityBuild/Editor/BuildActions` exists.

**Comment by Estemyr** [comment]
Perfect, thank you again for all help!
