### ISSUE TITLE
Problem with ZipFileOperation for large folders (+ possible solution)

### ISSUE THREAD

**Issue by 3ternal** [Chaser324/unity-build-actions#29]
I've previously used ZipFileOperation to create a zip for each of my builds, but I recently encountered a problem with this, possibly due to the project's current file size. Here's the error:

`Ionic.Zip.ZipException: Compressed or Uncompressed size, or offset exceeds the maximum value. Consider setting the UseZip64WhenSaving property on the ZipFile instance.`

The source folders are around 5.5 GB, and if I create a zip manually, it comes out to around 900 MB.

It seems like this could be solved by adding a line with the UseZip64WhenSaving property as the message suggests, but I can't easily test this myself because the script is part of the Unity package, so it auto-reverts any edits that I make.

**Comment by robinnorth** [comment]
Hi @3ternal, thanks for reporting this. I'll take a look into it, but it sounds like your suggestion might be the right way to go.
