### ISSUE TITLE
Storing the Butler path separately from the rest of the config

### ISSUE THREAD

**Issue by chemicalcrux** [Chaser324/unity-build-actions#30]
I work on both macOS and Windows and use the ItchUpload post-build action. The path to the Butler executable varies, so I have to remember to change it back and forth depending on where I'm building from.

It feels like the path should be stored separately from the rest of the configuration -- it's the only part of the configuration that has anything to do with your specific machine. Everything else is consistent, no matter where I'm working.

Perhaps it would go into the user settings? I'm not familiar with how that works.

**Comment by robinnorth** [comment]
Perhaps to avoid having to store any kind of machine-specific paths, the build action should instead require Butler to be accessible from your system path instead?

There's documentation on how to set that up at https://itch.io/docs/butler/installing.html#adding-butler-to-your-path, would be good to test if using a Butler executable path of just 'butler' in the build action works when this has been configured.

**Comment by chemicalcrux** [comment]
Ah, that's a reasonable idea. The path field could be left in case you do need to override it.
