### ISSUE TITLE
Failing build pre/post-actions should be flagged in the SuperUnityBuild window

### ISSUE THREAD

**Issue by nickfourtimes** [Chaser324/unity-build-actions#44]
I'm creating a custom IPostBuildPerPlatformAction, and it needs to check whether certain files/folders exist; if they do not, I want the SUB window to surface this in the log section, rather than assuming the user will _also_ be checking the Console for errors. Presently, if my post-build step prints to `Debug.LogError` and exits unexpectedly, the Log section of the SUB window still looks as though the build was successful (and only the Console shows the error).

Is there a better way to surface full-on errors/failures in pre- or post-build actions?

**Comment by robinnorth** [comment]
Hey @nickfourtimes, your build action can log an error to the SuperUnityBuild log like so:

```c#
BuildNotificationList.instance.AddNotification(new BuildNotification(
    BuildNotification.Category.Error,
    "Error title",
    "Error message"
));
```

You can use `BuildNotification.Category.Warning` for a warning, and `BuildNotification.Category.Notification` for an information-level log as well.

Take a look at the `FileUtility` build action for an example of this in action.

**Comment by nickfourtimes** [comment]
Oh perfect, this'll do nicely! Sorry if this was documented elsewhere & I just missed it.

**Comment by robinnorth** [comment]
@nickfourtimes you're most welcome! I don't believe it is documented anywhere, as the wiki is very out of date, I just know this from having reworked the File Utility action last year.
