### ISSUE TITLE
SteamWorks support

### ISSUE THREAD

**Issue by XaeroDegreaz** [Chaser324/unity-build-actions#8]
Hello again!

Do you have any plans to add any SteamWorks support?

**Comment by Chaser324** [comment]
What sort of SteamWorks functionality would you want?

In my mind, the ScriptRunner build action seems sufficient for this. The standard SteamWorks workflow already leads you to create a `run_build.bat` script and the `*.vdf` script files required by `steamcmd.exe`, so I think just pointing a ScriptRunner build action at that primary build script isn't much of a leap.

I suppose those `*.vdf` files could be generated, but that may get a bit messy in the case of people that have complex FileMapping options. I don't know what other options `steamcmd.exe` takes, but I guess there may be some room to allow specifying those - although this is again something that would be just as easy to setup with your own batch script.

**Comment by XaeroDegreaz** [comment]
Fair enough, I didn't really think of that.
